name: hello-world

on: push

jobs: 
  hello-world-job:

    runs-on: ubuntu-latest

    steps: 
      - name: Check out file content
        uses: actions/checkout@v3
      - run: echo "$(cat /etc/lsb-release)"
